export const USER_LOCALSTORAGE_KEY = "USER_LOCALSTORAGE_KEY";
export const USER_LOCALSTORAGE_REFRESH = "USER_LOCALSTORAGE_REFRESH";
export const ID_TOUR = "ID_TOUR";
export const ID_HOTEL = "ID_HOTEL";